spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:static/data.sqlite
    username:
    password:
  jdbc:
    template:
      fetch-size: -1
      max-rows: -1
      query-timeout: