server:
  port: 8085
spring:
  application:
    name: springboot-minio
minio:
  endpoint: http://192.168.10.20:9000
  port: 9000
  accessKey:  admin #Login Account
  secretKey:  thinker123 # Login Password
  secure: false
  bucket-name: commons # Bucket Name
  image-size: 10485760 #  Maximum size of picture file
  file-size: 1073741824 #  Maximum file size
